const product={id:'nvg',name:'Night Vision Goggles',desc:'อุปกรณ์มองกลางคืน เหมาะสำหรับภารกิจลับหรือบุกเวลากลางคืน',price:3500,stock:4};
const products=Array.from({length:10},(_,i)=>({...product,id:`nvg-${i}`,popular:i%5===0}));
const money=n=>`฿ ${n.toLocaleString('en-US',{minimumFractionDigits:2})}`;
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const state={page:'shop',dark:false,cart:[],orders:[{id:'85632007-13c8-40f5-952b-9c77edcc6d51',date:'26/5/2568 02:59:06',status:'ยกเลิกแล้ว',tx:'35307e92-646e-48b6-922d-d88dde3f6772',items:[{...product,qty:1},{...product,qty:1}]},{id:'2a21b707-f779-4ba0-acd4-06c5dc4cc8df',date:'26/5/2568 04:25:07',status:'รอชำระเงิน',tx:'548b1efd-4798-4e35-ad8a-2a06feff9167',items:[{...product,qty:1},{...product,qty:1}]}]};
const root=document.getElementById('root');
function setPage(page){state.page=page;render()} function toggleTheme(){state.dark=!state.dark;render()}
function addCart(qty=1,buy=false){state.cart.unshift({...product,qty,id:uid()}); if(buy)state.page='cart'; render()}
function createOrder(){if(!state.cart.length)return; state.orders.unshift({id:uid(),date:new Date().toLocaleString('th-TH'),status:'รอชำระเงิน',tx:uid(),items:[...state.cart]}); state.cart=[]; state.page='orders'; render()}
function header(){return `<header class="topbar"><button class="logo" data-page="shop"><span>EREAL</span><b>BOXSER</b></button><nav><button class="pill avatar">🪙 cvoppy</button><button class="pill">ออกจากระบบ</button><button class="icon" data-page="cart" aria-label="ตะกร้า">🛒</button><button class="icon" data-action="theme" aria-label="เปลี่ยนธีม">${state.dark?'☾':'☼'}</button></nav></header>`}
function shop(){return `<main class="container shop"><section class="hero"><button>‹</button><div></div><button>›</button></section><section class="stats">${[['ผู้ใช้งานทั้งหมด','ผู้ใช้งานทั้งหมด','4K'],['ผู้ใช้งานวันนี้','ผู้ใช้งานวันนี้','1.3K'],['ยอดซื้อทั้งหมด','ยอดซื้อทั้งหมด','10K'],['ยอดขายวันนี้','ยอดขายวันนี้','420']].map(s=>`<article><small>${s[0]}</small><strong>${s[1]}<em>${s[2]}</em></strong></article>`).join('')}</section><section class="grid">${products.map(p=>`<article class="card" data-modal="${p.id}"><div class="thumb"><span>${p.popular?'สินค้ายอดนิยม':''}</span></div><h3>${p.name}</h3><p>${p.desc}</p><b>${money(p.price)}</b></article>`).join('')}</section></main>`}
function modal(){return `<div class="overlay"><dialog open class="modal"><button class="close" data-close>×</button><div class="modal-img"></div><h2>${product.name}</h2><p>${product.desc}</p><div class="buyline"><strong>${money(product.price)}</strong><span>จำนวนคงเหลือ ${product.stock} ชิ้น</span></div><div class="actions"><input id="qty" type="number" min="1" max="${product.stock}" value="1"><button data-add>🛒 หยิบใส่ตะกร้า</button><button data-buy>▣ สั่งซื้อ</button></div></dialog></div>`}
function topup(){return `<main class="center"><h1>💳 เติมเงินและเพิ่มแต้ม</h1><input placeholder="ลิงค์อั่งเปา"><button>เติมเงิน</button></main>`}
function cart(){const total=state.cart.reduce((s,i)=>s+i.price*i.qty,0);return `<main class="container cart"><h1>ตะกร้าสินค้า</h1>${state.cart.map(i=>`<article class="cart-row"><div><h2>${i.name}</h2><p>${i.desc}</p><small>จำนวน ${i.qty}</small></div><strong>${money(i.price*i.qty)}</strong></article>`).join('')||'<p>ยังไม่มีสินค้าในตะกร้า</p>'}<h3>ราคารวมทั้งหมด <b>${money(total)}</b></h3><div class="cart-actions"><button data-order>▣ สั่งซื้อทั้งหมด</button><span></span><button data-page="topup">💸 เติมเงิน</button><button data-page="orders">▣ คำสั่งซื้อ</button></div></main>`}
function orders(){return `<main class="container orders"><h1>รายการคำสั่งซื้อ</h1>${state.orders.map(o=>`<section class="order"><div class="order-head"><div><h2>รหัสคำสั่งซื้อ: ${o.id}</h2><p>วันที่: ${o.date}</p><p>การชำระเงิน: <b class="${o.status==='ยกเลิกแล้ว'?'red':'blue'}">${o.status}</b></p></div><small>รหัสธุรกรรม:<br>${o.tx}</small></div>${o.items.map(i=>`<article class="order-item"><div><h3>${i.name}</h3><p>จำนวน: ${i.qty}</p></div><strong>${money(i.price*i.qty)}<small>(${i.price.toFixed(2)} x ${i.qty})</small></strong></article>`).join('')}<div class="order-actions"><button data-cancel="${o.id}">ยกเลิกคำสั่งซื้อ</button><button>ชำระเงิน</button></div></section>`).join('')}</main>`}
function render(){root.innerHTML=`<div class="app ${state.dark?'dark':''}">${header()}${state.page==='shop'?shop():state.page==='topup'?topup():state.page==='cart'?cart():orders()}<footer><button data-page="topup">เติมเงิน</button><button data-page="orders">คำสั่งซื้อ</button></footer></div>`; bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.querySelector('[data-action="theme"]')?.addEventListener('click',toggleTheme);document.querySelectorAll('[data-modal]').forEach(c=>c.onclick=()=>{document.body.insertAdjacentHTML('beforeend',modal());bindModal()});document.querySelector('[data-order]')?.addEventListener('click',createOrder);document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{state.orders=state.orders.map(o=>o.id===b.dataset.cancel?{...o,status:'ยกเลิกแล้ว'}:o);render()})}
function bindModal(){const ov=document.querySelector('.overlay'),qty=document.getElementById('qty');const close=()=>ov.remove();ov.onclick=e=>{if(e.target===ov)close()};document.querySelector('[data-close]').onclick=close;document.querySelector('[data-add]').onclick=()=>{addCart(Math.max(1,+qty.value||1));close()};document.querySelector('[data-buy]').onclick=()=>{addCart(Math.max(1,+qty.value||1),true);close()}}
render();
